# Generated by Django 3.2.2 on 2021-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='search',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
