# Generated by Django 3.2.2 on 2021-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Клиент'), ('crm_admin', 'Админ CRM')], default='customer', max_length=16, verbose_name='Тип пользователя'),
        ),
    ]
