# Generated by Django 3.2.2 on 2021-09-29 11:24

from django.db import migrations
from rest_framework.authtoken.models import Token

from apps.user.models import User


def create_crm_admin(a, b):
    user, created = User.objects.get_or_create(
        user_type=User.TYPE_CRM_ADMIN,
        phone_number='+996990111005',
        is_active=True,
    )
    Token.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_user_type'),
    ]

    operations = [
        migrations.RunPython(create_crm_admin)
    ]

