# Generated by Django 3.2.2 on 2021-12-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='imei',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
